### ISSUE TITLE
Default language should be english

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-api#10]
If browser language is not chinese the default  should be english

**Comment by LaurentSalou** [comment]
Done on dev branch of mvs-explorer-www
Check the first language in the languages preferences of the browser via navigator.languages
If it's start with 'zh' set the language to Chinese, otherwise set it to English

![lang](https://user-images.githubusercontent.com/29446660/37394291-5559f17c-27ae-11e8-9275-da7beb9ee819.png)

**Comment by canguruhh** [comment]
nice
