### ISSUE TITLE
List of assets

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-api#2]
A searchable list of all assets on Metaverse with information on the asset like:
- total supply
- symbol
- description
- link to issue transaction

**Comment by LaurentSalou** [comment]
![assetspage](https://user-images.githubusercontent.com/29446660/37270437-c55cff6a-2609-11e8-916f-c79718013d71.png)
The #!/assets page has been added. Click on the Asset symbol link to the issue transaction

I have also changed the top bar in order to navigate between the pages

Via the API, the list of assets is accessible via /api/assets
